test-updated-deployment checks are corrected

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -588,7 +588,7 @@ jobs:
             out=$(curl -s http://localhost:5000)
             echo $out
             appinfo=$(echo $out | cut -d"," -f1)
-            if [[ $appinfo == "app-version=v1" ]]; then echo "app version info check passed"; else echo "app version info check failed" && exit 1; fi
+            if [[ $appinfo == "app-version=v2" ]]; then echo "app version info check passed"; else echo "app version info check failed" && exit 1; fi
             pageinfo=$(echo $out | cut -d"," -f2)
             if [[ $pageinfo =~ page-counter.* ]]; then echo "page counter check passed"; else echo "page counter check failed"; fi
             newfeatures_info=$(echo $out | cut -d"," -f3)
